version: "3.9"

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      # Mount the local src folder so changes appear immediately
      - ./src:/usr/share/nginx/html:ro
      # Mount custom Nginx config to disable caching
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
